[package]
name = "apalis-core"
version = "0.2.0"
authors = ["Geoffrey Mureithi <mureithinjuguna@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Core for Apalis: simple and reliable background processing for Rust for Actix"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2.5.0"
actix = "0.12.0"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
log = "0.4"
rmp-serde = "0.14"
env_logger = "0.7"
fnv = "1.0.3"
uuid = { version = "0.8", features = ["serde", "v4"] }
tokio = { version = "1", features = ["sync"] }