[package]
name = "apalis-redis"
version = "0.2.0"
authors = ["Geoffrey Mureithi <mureithinjuguna@gmail.com>"]
edition = "2018"

license = "MIT"
description = "Redis Storage for Apalis: simple and reliable background processing based on Actix Actors"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2.5.0"
actix = "0.12.0"
apalis-core = { path = "../../packages/apalis-core", version = "0.2" }
redis = { version = "0.20.0" , features = ["async-std-comp"] }
serde = "1"
log = "0.4"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "0.8", features = ["serde", "v4"] }